project:
  type: book

book:
  title: "HSItools documentation"
  author: "Maurycy Żarczyński"
  date: "`r Sys.time()`"
  chapters:
    - index.qmd
    - intro.qmd
    - shiny.qmd
    - preprocessing.qmd
    - rois.qmd
    - indices.qmd
    - visualizing.qmd
    - extracting.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: flatly
  pdf:
    documentclass: scrreprt

editor: visual

